name: 3D Contribution Graph
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install github-profile-3d-contrib
        run: npm install -g github-profile-3d-contrib

      - name: Generate 3D Contribution Graph
        run: github-profile-3d-contrib --username cssidhu0001 --output ./profile-3d-contrib/profile-night-rainbow.svg

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add ./profile-3d-contrib/profile-night-rainbow.svg
          git commit -m "Update 3D contribution graph" || echo "No changes to commit"
          git push
