name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # daily at 6 PM UTC (11:30 PM IST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contribution graphs (light & dark)
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # 🌞 Light Theme
      - name: Generate Light Theme Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: cssidhu0001
          THEME: light_green
          OUTPUT_PATH: ./profile-3d-contrib/profile-3d-light.svg

      # 🌚 Dark Theme
      - name: Generate Dark Theme Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: cssidhu0001
          THEME: dark_green
          OUTPUT_PATH: ./profile-3d-contrib/profile-3d-dark.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "Generated: 3D contribution graphs (light & dark)"; then
            git push
          else
            echo "No changes to commit"
          fi
