name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"    # once per day (change if you want)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: cssidhu0001
          # If you create a settings JSON (optional), uncomment and set its path:
          # SETTING_JSON: ./profile-3d-settings.json

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated: 3D contribution graph"; then
            git push
          else
            echo "No changes to commit"
          fi
